[webhook]
webhook=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=23db8324-42a5-4c25-b662-ed307b920abd

[url]
url=url.txt

[timeout]
timeout=10

[moban]
moban=【网站监控告警】
时间: {timestamp}
网站: {url}
描述: {description}
状态: {status_code}
结果: 无法访问

[logfile]
logfile=./logs
